config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  
  get 'about', to: 'pages#about'
  get  'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to:'sessions#destroy'
  
  get 'signup', to: 'users#new'

  resources :users, except: [:new]
  
  resources :employee_tables
  resources :students

  
  get 'employee/list'
  get 'employee/create'
  get 'employee/read'
  get 'employee/update'
  get 'employee/delete'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :user

  validates :name , presence: true
  validates :age , presence: true
  validates :city , presence: true
  validates :Address , presence: true
  validates :postal_code , presence: true
  validates :user_id, presence: true
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  before_action :set_student,  only: [:edit, :update, :show, :destroy]

  before_action :require_user, except: [:index, :show]

  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index 
    @students= Student.paginate(page: params[:page])
  end 


  def new 
    @student =Student.new

    # render json: { html: render_to_string(partial: 'form') }
  end



  def edit
    
  end 

  def update
    
      if @student.update(student_params)
        flash[:success] = "Student was successfully updated"
        redirect_to student_path(@student)
      else 
        render 'edit'
      end
  end
  
  
  def create 
    #   byebug
    # render html: params[:student].inspect
    @student =Student.new(student_params)
    @student.user = current_user
      if @student.save
        flash[:success]="student is created"
        redirect_to student_path(@student)
      else
        render 'new'
      end
  
  end

  def destroy
    
    @student.destroy
    flash[:danger] = "student is successfully deleted"

    redirect_to students_path
  end 
  def show
    #byebug
    
    puts "#{@student}"
  end
 
   

  private
    def set_student
      @student = Student.find(params[:id])
    end
    
    def student_params
      params.require(:student).permit(:name,:age,:city,:Address,:postal_code)
    end
    
    def require_same_user
      if current_user !=@student.user and !current_user.admin?
        flash[:danger] ="you can edit or delete your own students"
        redirect_to root_path
      end
    end
  
  end

app/views/students/_form.html.erb
<%= render 'shared/errors',obj: @student%>

<div class='row' id='newForm'>
  <div class='col-xs-12'>
    <%= form_for(@student, :html => {class: "form-horizontal", role: "form"}) do |f|%>
      <div class="form-group">
        <div class="control-label col-sm-2">
            <%= f.label :name %>
          </div>
          <div class="col-sm-8">
            <%= f.text_field :name, class:"form-control",placeholder: "name of student", autofocus: true %>
            </div>
          </div>
      
      <div class="form-group">
        <div class="control-label col-sm-2">
            <%= f.label :age %>
            </div>
            <div class="col-sm-8">
              <%= f.text_field :age, class:"form-control",placeholder: "name of student", autofocus: true %>
              </div>
        </div>
        
         <div class="form-group">
          <div class="control-label col-sm-2">
              <%= f.label :city %>
            </div>
            <div class="col-sm-8">
                <%= f.text_field :city, class:"form-control",placeholder: "name of student", autofocus: true %>
                </div>
        </div>
        
        <div class="form-group">
          <div class="control-label col-sm-2">
            <%= f.label :Address %>
          </div>
            <div class="col-sm-8">
              <%= f.text_field :Address, class:"form-control",placeholder: "name of student", autofocus: true%>
              </div>
        </div>
        
          <div class="form-group">
            <div class="control-label col-sm-2">
              <%= f.label :postal_code %>
            </div>
            <div class="col-sm-8">
                <%= f.text_field :postal_code, class:"form-control",placeholder: "name of student", autofocus: true %>
              </div>
        </div>

        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit class: 'btn btn-primary btn-lg', id:"btnsubmit" %>
          </div>
        </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">
    [ <%= link_to "cancel request and return to students listing", students_path %> ]
    </div>
  </div>
</div>

app/views/students/_student.html.erb
<% obj.each do |student| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="student-name">
          <%= link_to student.name, student_path(student) %>
        </div>
            <div class="student-body">
              <td><%= student.city %></td>
              <%
=begin%>
 <div class="student-meta-details">
              <small>created by: <%= student.user.username if student.user %>, <%= time_ago_in_words(student.created_at) %> ago,last updated:<%= time_ago_in_words(student.updated_at) %> ago </small>
              </div> 
<%
=end%>
              <% if logged_in? && (current_user == student.user || current_user.admin?) %>
                <div class="student-actions">
                <%= link_to "Edit this student", edit_student_path(student),class: "btn btn-xs btn-primary" %>
                <%= link_to "delete this student ",student_path(student), method: :delete, 
                    data:{confirm: "are you really sure to delete the sudent ??"}, class: "btn btn-xs btn-danger" %>
                </div>
                <% end %>
             </div>
       </div>
      </div>       
     </div> 
    </div>    
  </div> 
<% end %>

app/views/students/edit.html.erb
<h1 align="center">Edit Student Information</h1>

<%= render 'form' %>

app/views/students/index.html.erb
<h1 align="center"> ALL STUDENTS RECORDS</h1>
<%
=begin%>
 <div align="center">
  <%= will_paginate %>
</div> 
<%
=end%>
<%= render 'student',obj: @students %>

app/views/students/new.html.erb
<h1 align="center"> create a student </h1>

 <%= render 'form' %> 

app/views/students/show.html.erb
<h2 align="center"> Name: <%= @student.name %></h2>

<div class="well col-xs-8 col-xs-offset-2">
  <% if @student.user %>
  <ul class="listing">
      <div class ="row center">
        <div class = "col-md-4 col-md-offset-4">
        <li>Created by:</li>
        <li><%= link_to gravatar_for(@student.user), user_path(@student.user) %></li>
        <li>
          <%= link_to @student.user.username, user_path(@student.user) %>
        </li>

        <li><small><%= pluralize(@student.user.students.count, "student") if @student.user.students %></small></li>
        </div>
      </div>
   </ul>
  <% end %>
  <h4 class="center texts"><strong>  student's age:</strong></h4>
  <hr>
  <%= simple_format(@student.age) %>
    <div class="student-actions">
      <% if logged_in? && (current_user == @student.user || current_user.admin?) %>
      <%= link_to "Edit this student", edit_student_path(@student),class: "btn btn-xs btn-primary" %>

<%
=begin%>
 <%= link_to "edit this student's details", edit_student_path(@student) %> | 
<%
=end%>
      <%= link_to "delete this student ",student_path(@student), method: :delete, data:{confirm: "are you really sure to delete the sudent ??"}, class: "btn btn-xs btn-danger" %>
      <% end %>
      <%= link_to "back to Student lists", students_path, class: "btn btn-xs btn-success" %>
    </div>
  </div>