config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  
  get 'about', to: 'pages#about'
  get  'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to:'sessions#destroy'
  
  get 'signup', to: 'users#new'

  resources :users, except: [:new]
  
  resources :employee_tables
  resources :students

  
  get 'employee/list'
  get 'employee/create'
  get 'employee/read'
  get 'employee/update'
  get 'employee/delete'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/employee_tables_controller.rb
class EmployeeTablesController < ApplicationController
  before_action :set_employee_table, only: [:show, :edit, :update, :destroy]


  # GET /employee_tables
  # GET /employee_tables.json
  def index
    @employee_tables = EmployeeTable.all
  end

  # GET /employee_tables/1
  # GET /employee_tables/1.json
  def show
  end

  # GET /employee_tables/new
  def new
    @employee_table = EmployeeTable.new
  end

  # GET /employee_tables/1/edit
  def edit
  end

  # POST /employee_tables
  # POST /employee_tables.json
  def create
    byebug
    @employee_table = EmployeeTable.new(employee_table_params)

    respond_to do |format|
      if @employee_table.save
        format.html { redirect_to @employee_table, notice: 'Employee table was successfully created.' }
        format.json { render :show, status: :created, location: @employee_table }
      else
        format.html { render :new }
        format.json { render json: @employee_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employee_tables/1
  # PATCH/PUT /employee_tables/1.json
  def update
    respond_to do |format|
      if @employee_table.update(employee_table_params)
        format.html { redirect_to @employee_table, notice: 'Employee table was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee_table }
      else
        format.html { render :edit }
        format.json { render json: @employee_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employee_tables/1
  # DELETE /employee_tables/1.json
  def destroy
    @employee_table.destroy
    respond_to do |format|
      format.html { redirect_to employee_tables_url, notice: 'Employee table was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # private
  #   # Use callbacks to share common setup or constraints between actions.
  #   def set_employee_table
  #     @employee_table = EmployeeTable.find(params[:id])
  #   end

  #   # Never trust parameters from the scary internet, only allow the white list through.
  #   def employee_table_params
  #     params.require(:employee_table).permit(:name, :email, :address)
  #   end
end

app/helpers/employee_tables_helper.rb
module EmployeeTablesHelper
end

app/views/employee_tables/_form.html.erb
<%= form_with(model: employee_table, local: true) do |form| %>
  <% if employee_table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee_table.errors.count, "error") %> prohibited this employee_table from being saved:</h2>

      <ul>
      <% employee_table.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/employee_tables/edit.html.erb
<h1>Editing Employee Table</h1>

<%= render 'form', employee_table: @employee_table %>

<%= link_to 'Show', @employee_table %> |
<%= link_to 'Back', employee_tables_path %>

app/views/employee_tables/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employee Tables</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employee_tables.each do |employee_table| %>
      <tr>
        <td><%= employee_table.name %></td>
        <td><%= employee_table.email %></td>
        <td><%= employee_table.address %></td>
        <td><%= link_to 'Show', employee_table %></td>
        <td><%= link_to 'Edit', edit_employee_table_path(employee_table) %></td>
        <td><%= link_to 'Destroy', employee_table, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee Table', new_employee_table_path %>

app/views/employee_tables/new.html.erb
<h1>New Employee Table</h1>

<%= render 'form', employee_table: @employee_table %>

<%= link_to 'Back', employee_tables_path %>

app/views/employee_tables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @employee_table.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @employee_table.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @employee_table.address %>
</p>

<%= link_to 'Edit', edit_employee_table_path(@employee_table) %> |
<%= link_to 'Back', employee_tables_path %>