config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  
  get 'about', to: 'pages#about'
  get  'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to:'sessions#destroy'
  
  get 'signup', to: 'users#new'

  resources :users, except: [:new]
  
  resources :employee_tables
  resources :students

  
  get 'employee/list'
  get 'employee/create'
  get 'employee/read'
  get 'employee/update'
  get 'employee/delete'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="class">
    <small>
      Copyright &copy; by <a>harshj</a>
      </small>
      <nav>
        <ul>
          <li><%= link_to "about ",about_path %></li>
        </ul>
      </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class ="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name ,msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id=>"flash_#{name}" if msg. is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%
=begin%>
 <a class="navbar-brand" id="logo" href="#">Person Management</a> 
<%
=end%>
      <%= link_to "Person Management", root_path, class: "navbar-brand",id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <%
=begin%>
 <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li> 
<%
=end%>
        <li><%= link_to "Students", students_path %></li>
        <li><%= link_to "Users", users_path %></li>
      
      <% if logged_in? %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <%
=begin%>
<li><a href="#">Action</a></li> 
<%
=end%>
          <li><%= link_to "New Student" ,new_student_path %></li>
          <li><a href="#">Another action</a></li>
          <li><a href="#">Something else here</a></li>
          <li role="separator" class="divider"></li>
          <li><a href="#">Separated link</a></li>
          <li role="separator" class="divider"></li>
          <li><a href="#">One more separated link</a></li>
        </ul>
      </li>
      <% end %>

      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
      <% if logged_in? %> 
            <li><%= link_to 'log out',logout_path, method: :delete %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile <%= "Admin" if current_user.admin? %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Edit you profile",edit_user_path(current_user) %></li>
                <li><%= link_to "View your profile", user_path(current_user)%></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Separated link</a></li>
              </ul>
            </li>
      <% else %>

            <li><%= link_to 'Login',login_path %></li>
            <li><%= link_to 'Sign Up',signup_path %></li>
            
      <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmployeeManagement</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.develpment? %>
  </body>
</html>